locals {
  dedicated = var.hosting_model == "dedicated"

  # Names the platform's own resources already use. A service called one of these
  # could otherwise generate a resource name that collides with -- and, through a
  # name-pattern permission, reach -- core's own (for example the database hub's
  # secret, or the fleet-update SSM document).
  # "team-tools" is the Service tag of the team's own tools, whose role is
  # generated by tools-role: a service of that name would share its tag, and so
  # its permissions.
  reserved_service_names = ["database", "database-hub", "fleet", "internal", "platform", "private", "services", "team-tools"]

  # Whole families of names. "database-" is the platform's database secrets
  # (<project>-database-admin-<engine>-..., -database-people-...), which the
  # fleets are denied by that prefix. People's database logins need no reserved
  # name: they are <scope>.<name>, and a service's user never contains a dot.
  reserved_service_prefixes = ["database-"]

  entry_keys = [for repository, entry in var.entries : "${entry.kind}/${entry.service_name}"]

  invalid_repository_keys = [
    for repository, entry in var.entries : repository
    if !can(regex("^[A-Za-z0-9-]+/[A-Za-z0-9._-]+$", repository))
  ]

  invalid_kinds = [
    for repository, entry in var.entries : repository
    if !contains(["app", "infra"], entry.kind)
  ]

  # Service names that cannot be used in resource names. The generated target
  # group name (<project>-<service>-<environment>-tg) is limited to 32 characters
  # by AWS.
  invalid_service_names = [
    for repository, entry in var.entries : entry.service_name
    if !can(regex("^[a-z][a-z0-9-]{1,20}[a-z0-9]$", entry.service_name))
    || length("${var.project_name}-${entry.service_name}-${var.environment}-tg") > 32
  ]

  reserved_names_used = [
    for repository, entry in var.entries : entry.service_name
    if contains(local.reserved_service_names, entry.service_name)
    || anytrue([for prefix in local.reserved_service_prefixes : startswith(entry.service_name, prefix)])
  ]

  entries_with_unknown_tier = [
    for repository, entry in var.entries : repository
    if !contains(keys(var.tiers), entry.tier)
  ]

  # A service's two repositories must agree on the tier they are placed in.
  tiers_by_service = {
    for name in distinct([for repository, entry in var.entries : entry.service_name]) :
    name => distinct([for repository, entry in var.entries : entry.tier if entry.service_name == name])
  }

  services_with_conflicting_tiers = [for name, tiers in local.tiers_by_service : name if length(tiers) > 1]

  has_entries = length(var.entries) > 0
  has_infra   = anytrue([for repository, entry in var.entries : entry.kind == "infra"])

  missing_inputs = local.has_entries ? concat(
    [
      for name, value in {
        assets_bucket_name = var.assets_bucket_name
        state_bucket_name  = var.state_bucket_name
      } : name if value == null
    ],
    local.dedicated ? [] : [
      for name, value in {
        deploy_bucket_name         = var.deploy_bucket_name
        fleet_update_document_name = var.fleet_update_document_name
      } : name if value == null
    ],
    local.dedicated && local.has_infra && var.permissions_boundary_arn == null ? ["permissions_boundary_arn"] : [],
  ) : []

  # Shared-fleet infra entries need the fleet's own ASG and security group.
  infra_missing_fleet_resources = local.dedicated ? [] : [
    for repository, entry in var.entries : repository
    if entry.kind == "infra" && contains(keys(var.tiers), entry.tier)
    && (try(var.tiers[entry.tier].asg_arn, null) == null || try(var.tiers[entry.tier].security_group_id, null) == null)
  ]

  ra           = "${var.aws_region}:${var.account_id}"
  iam          = "arn:aws:iam::${var.account_id}"
  boundary_arn = coalesce(var.permissions_boundary_arn, "${local.iam}:policy/platform/unset")

  # Everything each entry's policy names, computed once.
  ctx = {
    for repository, entry in var.entries : repository => {
      kind    = entry.kind
      service = entry.service_name
      tier    = entry.tier

      # <project>-<service>-<environment>: the order terraform-aws-secrets-vault
      # and terraform-aws-target-group v1 give the secret and the target group. It
      # is the ONE exception to <project>-<environment>-<service>, and goes when
      # those two modules release a v2 that follows the rule.
      service_first_prefix = "${var.project_name}-${entry.service_name}-${var.environment}"

      listener_arn = var.tiers[entry.tier].listener_arn
      rule_arns    = "${replace(var.tiers[entry.tier].listener_arn, ":listener/", ":listener-rule/")}/*"
      asg_arn      = coalesce(try(var.tiers[entry.tier].asg_arn, null), "unset")
      sg_id        = coalesce(try(var.tiers[entry.tier].security_group_id, null), "unset")

      config_bucket = "${var.project_name}-${var.environment}-${entry.service_name}-config"
    }
    if contains(keys(var.tiers), entry.tier)
  }

  # A service's infra repository can provision its database only where there is a
  # database host to provision on, which is the shared environment. A
  # dedicated environment uses a managed database, which has no container to run
  # the provisioning in; that mechanism does not exist yet.
  provisioning_enabled = !local.dedicated && var.database_provision_document_name != null && var.deploy_bucket_name != null

  # On a managed database there is no host to send a document to: the service's
  # infra repository invokes core's provisioning function instead.
  managed_provisioning_enabled = length(var.database_provision_function_arns) > 0

  deploy_bucket = coalesce(var.deploy_bucket_name, "unset")
  assets_bucket = coalesce(var.assets_bucket_name, "unset")
  state_bucket  = coalesce(var.state_bucket_name, "unset")
  fleet_doc     = coalesce(var.fleet_update_document_name, "unset")

  ##############################################################################
  # STATEMENTS -- constants
  ##############################################################################

  st_ecr_login = jsonencode({
    Sid      = "EcrLogin"
    Effect   = "Allow"
    Action   = ["ecr:GetAuthorizationToken"]
    Resource = "*"
  })

  st_lookups_app = jsonencode({
    Sid    = "ReadOnlyLookups"
    Effect = "Allow"
    Action = [
      "ec2:DescribeInstances", "ssm:DescribeInstanceInformation", "ssm:GetCommandInvocation",
      "ssm:ListCommandInvocations", "ssm:ListCommands",
    ]
    Resource = "*"
  })

  st_lookups_infra = jsonencode({
    Sid    = "ReadOnlyLookups"
    Effect = "Allow"
    Action = [
      "autoscaling:Describe*", "ec2:Describe*", "elasticloadbalancing:Describe*",
      "ssm:DescribeDocument", "ssm:DescribeParameters",
    ]
    Resource = "*"
  })

  ##############################################################################
  # STATEMENTS -- per entry
  ##############################################################################

  # ---- app: what the deploying repository does -------------------------------

  st_ecr_push = {
    for repository, c in local.ctx : repository => jsonencode({
      Sid    = "EcrPushOwnRepository"
      Effect = "Allow"
      Action = [
        "ecr:BatchCheckLayerAvailability", "ecr:BatchGetImage", "ecr:CompleteLayerUpload",
        "ecr:DescribeImages", "ecr:GetDownloadUrlForLayer", "ecr:InitiateLayerUpload",
        "ecr:ListImages", "ecr:PutImage", "ecr:UploadLayerPart",
      ]
      Resource = "arn:aws:ecr:${local.ra}:repository/${c.service}/*"
    })
  }

  st_read_platform = {
    for repository, c in local.ctx : repository => jsonencode({
      Sid    = "ReadPlatformAndServiceConfig"
      Effect = "Allow"
      Action = ["ssm:GetParameter", "ssm:GetParameters", "ssm:GetParametersByPath"]
      Resource = [
        "arn:aws:ssm:${local.ra}:parameter/${var.project_name}/platform",
        "arn:aws:ssm:${local.ra}:parameter/${var.project_name}/platform/*",
        "arn:aws:ssm:${local.ra}:parameter/${var.project_name}/database/*",
        "arn:aws:ssm:${local.ra}:parameter/${var.project_name}/services/${c.service}/*",
      ]
    })
  }

  st_static = {
    for repository, c in local.ctx : repository => [
      jsonencode({
        Sid      = "StaticAssetsOwnPrefix"
        Effect   = "Allow"
        Action   = ["s3:DeleteObject", "s3:GetObject", "s3:PutObject"]
        Resource = "arn:aws:s3:::${local.assets_bucket}/static/${c.service}/*"
      }),
      jsonencode({
        Sid       = "StaticAssetsList"
        Effect    = "Allow"
        Action    = ["s3:GetBucketLocation", "s3:ListBucket"]
        Resource  = "arn:aws:s3:::${local.assets_bucket}"
        Condition = { StringLike = { "s3:prefix" = ["static/${c.service}", "static/${c.service}/*"] } }
      }),
    ]
  }

  # Publishing the compose file and env, and triggering the redeploy.
  st_app_hosting = {
    for repository, c in local.ctx : repository => local.dedicated ? [
      jsonencode({
        Sid      = "ConfigBucketPublish"
        Effect   = "Allow"
        Action   = ["s3:DeleteObject", "s3:GetObject", "s3:PutObject"]
        Resource = "arn:aws:s3:::${c.config_bucket}/*"
      }),
      jsonencode({
        Sid      = "ConfigBucketList"
        Effect   = "Allow"
        Action   = ["s3:GetBucketLocation", "s3:ListBucket"]
        Resource = "arn:aws:s3:::${c.config_bucket}"
      }),
      jsonencode({
        Sid      = "SendThisServicesUpdateDocumentOnly"
        Effect   = "Allow"
        Action   = ["ssm:SendCommand"]
        Resource = "arn:aws:ssm:${local.ra}:document/${var.project_name}-${c.service}-update"
      }),
      jsonencode({
        Sid      = "SendOnlyToThisServicesHosts"
        Effect   = "Allow"
        Action   = ["ssm:SendCommand"]
        Resource = "arn:aws:ec2:${local.ra}:instance/*"
        Condition = {
          StringEquals = {
            "ssm:resourceTag/Project" = var.project_name
            "ssm:resourceTag/Service" = c.service
          }
        }
      }),
      ] : [
      jsonencode({
        Sid      = "DeployBucketOwnPrefix"
        Effect   = "Allow"
        Action   = ["s3:DeleteObject", "s3:GetObject", "s3:PutObject"]
        Resource = "arn:aws:s3:::${local.deploy_bucket}/${c.tier}/${c.service}/*"
      }),
      jsonencode({
        Sid       = "DeployBucketList"
        Effect    = "Allow"
        Action    = ["s3:GetBucketLocation", "s3:ListBucket"]
        Resource  = "arn:aws:s3:::${local.deploy_bucket}"
        Condition = { StringLike = { "s3:prefix" = ["${c.tier}/${c.service}", "${c.tier}/${c.service}/*"] } }
      }),
      jsonencode({
        Sid      = "SendFleetUpdateDocumentOnly"
        Effect   = "Allow"
        Action   = ["ssm:SendCommand"]
        Resource = "arn:aws:ssm:${local.ra}:document/${local.fleet_doc}"
      }),
      jsonencode({
        Sid      = "SendOnlyToThisTiersHosts"
        Effect   = "Allow"
        Action   = ["ssm:SendCommand"]
        Resource = "arn:aws:ec2:${local.ra}:instance/*"
        Condition = {
          StringEquals = {
            "ssm:resourceTag/Project" = var.project_name
            "ssm:resourceTag/Service" = c.tier
          }
        }
      }),
    ]
  }

  # ---- infra: what the Terraform repository does -----------------------------

  st_infra_common = {
    for repository, c in local.ctx : repository => [
      jsonencode({
        Sid    = "EcrOwnRepository"
        Effect = "Allow"
        Action = [
          "ecr:CreateRepository", "ecr:DeleteLifecyclePolicy", "ecr:DeleteRepository", "ecr:DescribeRepositories",
          "ecr:GetLifecyclePolicy", "ecr:ListTagsForResource", "ecr:PutImageScanningConfiguration",
          "ecr:PutImageTagMutability", "ecr:PutLifecyclePolicy", "ecr:TagResource", "ecr:UntagResource",
        ]
        Resource = "arn:aws:ecr:${local.ra}:repository/${c.service}/*"
      }),
      jsonencode({
        Sid      = "SecretsOwnVault"
        Effect   = "Allow"
        Action   = ["secretsmanager:*"]
        Resource = "arn:aws:secretsmanager:${local.ra}:secret:${c.service_first_prefix}-secret-vault-*"
      }),
      jsonencode({
        Sid    = "TargetGroupOwn"
        Effect = "Allow"
        Action = [
          "elasticloadbalancing:AddTags", "elasticloadbalancing:CreateTargetGroup",
          "elasticloadbalancing:DeleteTargetGroup", "elasticloadbalancing:ModifyTargetGroup",
          "elasticloadbalancing:ModifyTargetGroupAttributes", "elasticloadbalancing:RemoveTags",
        ]
        Resource = "arn:aws:elasticloadbalancing:${local.ra}:targetgroup/${c.service_first_prefix}-tg/*"
      }),
      jsonencode({
        Sid       = "ListenerRuleCreateTaggedForThisService"
        Effect    = "Allow"
        Action    = ["elasticloadbalancing:CreateRule"]
        Resource  = c.listener_arn
        Condition = { StringEquals = { "aws:RequestTag/Service" = c.service } }
      }),
      jsonencode({
        Sid      = "ListenerRuleTagOnCreate"
        Effect   = "Allow"
        Action   = ["elasticloadbalancing:AddTags"]
        Resource = c.rule_arns
        Condition = {
          StringEquals = {
            "elasticloadbalancing:CreateAction" = "CreateRule"
            "aws:RequestTag/Service"            = c.service
          }
        }
      }),
      jsonencode({
        Sid    = "ListenerRuleManageOnlyThisServicesRules"
        Effect = "Allow"
        Action = [
          "elasticloadbalancing:AddTags", "elasticloadbalancing:DeleteRule", "elasticloadbalancing:ModifyRule",
          "elasticloadbalancing:RemoveTags", "elasticloadbalancing:SetRulePriorities",
        ]
        Resource  = c.rule_arns
        Condition = { StringEquals = { "aws:ResourceTag/Service" = c.service } }
      }),
      # Every service's Terraform discovers the platform through this parameter.
      jsonencode({
        Sid      = "ReadPlatformContract"
        Effect   = "Allow"
        Action   = ["ssm:GetParameter", "ssm:GetParameters"]
        Resource = ["arn:aws:ssm:${local.ra}:parameter/${var.project_name}/platform", "arn:aws:ssm:${local.ra}:parameter/${var.project_name}/platform/*"]
      }),
      # The one place the two repositories meet.
      jsonencode({
        Sid    = "ServiceConfigParameter"
        Effect = "Allow"
        Action = [
          "ssm:AddTagsToResource", "ssm:DeleteParameter", "ssm:GetParameter", "ssm:GetParameters",
          "ssm:ListTagsForResource", "ssm:PutParameter", "ssm:RemoveTagsFromResource",
        ]
        Resource = "arn:aws:ssm:${local.ra}:parameter/${var.project_name}/services/${c.service}/*"
      }),
      jsonencode({
        Sid      = "StateOwnPrefix"
        Effect   = "Allow"
        Action   = ["s3:DeleteObject", "s3:GetObject", "s3:PutObject"]
        Resource = "arn:aws:s3:::${local.state_bucket}/${var.state_prefix}/${c.service}/*"
      }),
      jsonencode({
        Sid       = "StateList"
        Effect    = "Allow"
        Action    = ["s3:GetBucketLocation", "s3:ListBucket"]
        Resource  = "arn:aws:s3:::${local.state_bucket}"
        Condition = { StringLike = { "s3:prefix" = ["${var.state_prefix}/${c.service}", "${var.state_prefix}/${c.service}/*"] } }
      }),
    ]
  }

  # Provisioning the service's own database: publish the request, then send the one
  # document that carries it out, and only to the database host.
  # The objects carry tags (the blueprint's own and the provider's default_tags), and
  # a PutObject with tags also needs s3:PutObjectTagging; the provider reads tags on
  # refresh and removes them on update. Same keys, so no wider.
  st_infra_provisioning = {
    for repository, c in local.ctx : repository => local.provisioning_enabled ? [
      jsonencode({
        Sid      = "PublishOwnProvisioningRequest"
        Effect   = "Allow"
        Action   = ["s3:DeleteObject", "s3:DeleteObjectTagging", "s3:GetObject", "s3:GetObjectTagging", "s3:PutObject", "s3:PutObjectTagging"]
        Resource = "arn:aws:s3:::${local.deploy_bucket}/provisioning/${c.service}/*"
      }),
      jsonencode({
        Sid      = "SendDatabaseProvisionDocumentOnly"
        Effect   = "Allow"
        Action   = ["ssm:SendCommand"]
        Resource = "arn:aws:ssm:${local.ra}:document/${coalesce(var.database_provision_document_name, "unset")}"
      }),
      jsonencode({
        Sid      = "SendOnlyToTheDatabaseHost"
        Effect   = "Allow"
        Action   = ["ssm:SendCommand"]
        Resource = "arn:aws:ec2:${local.ra}:instance/*"
        Condition = {
          StringEquals = {
            "ssm:resourceTag/Project" = var.project_name
            "ssm:resourceTag/Service" = var.database_service_name
          }
        }
      }),
      jsonencode({
        Sid    = "FollowItsOwnProvisioningCommand"
        Effect = "Allow"
        Action = ["ssm:GetCommandInvocation", "ssm:ListCommandInvocations", "ssm:ListCommands"]
        # AWS does not scope these to a command, so they are read-only by nature.
        Resource = "*"
      }),
    ] : []
  }

  # The front door: the service declares its agents' emails in its own file,
  # and core's function turns every declaration into sign-ins. One object, named
  # after the service: a service can neither read nor change another's.
  st_infra_front_door = {
    for repository, c in local.ctx : repository => var.front_door_enabled && var.deploy_bucket_name != null ? [
      jsonencode({
        Sid      = "DeclareOwnAgentsToTheFrontDoor"
        Effect   = "Allow"
        Action   = ["s3:DeleteObject", "s3:DeleteObjectTagging", "s3:GetObject", "s3:GetObjectTagging", "s3:PutObject", "s3:PutObjectTagging"]
        Resource = "arn:aws:s3:::${local.deploy_bucket}/front-door/${c.service}.json"
      }),
    ] : []
  }

  # Managed database: invoke core's provisioning function, and nothing else. The
  # function derives everything from the service name it is given, so invoking it
  # for another service only re-runs that service's own provisioning.
  st_infra_managed_provisioning = {
    for repository, c in local.ctx : repository => local.managed_provisioning_enabled ? [
      jsonencode({
        Sid      = "InvokeDatabaseProvisioning"
        Effect   = "Allow"
        Action   = ["lambda:InvokeFunction"]
        Resource = var.database_provision_function_arns
      }),
    ] : []
  }

  # Shared fleet: attach to the fleet's ASG and open a port on its security group.
  st_infra_shared = {
    for repository, c in local.ctx : repository => [
      jsonencode({
        Sid    = "AttachToTierAutoScalingGroup"
        Effect = "Allow"
        Action = [
          "autoscaling:AttachLoadBalancerTargetGroups", "autoscaling:DescribeLoadBalancerTargetGroups",
          "autoscaling:DetachLoadBalancerTargetGroups",
        ]
        Resource = c.asg_arn
      }),
      jsonencode({
        Sid    = "TierSecurityGroupIngress"
        Effect = "Allow"
        Action = [
          "ec2:AuthorizeSecurityGroupIngress", "ec2:ModifySecurityGroupRules", "ec2:RevokeSecurityGroupIngress",
        ]
        Resource = [
          "arn:aws:ec2:${local.ra}:security-group/${c.sg_id}",
          "arn:aws:ec2:${local.ra}:security-group-rule/*",
        ]
      }),
      jsonencode({
        Sid      = "TagSecurityGroupRules"
        Effect   = "Allow"
        Action   = ["ec2:CreateTags", "ec2:DeleteTags"]
        Resource = "arn:aws:ec2:${local.ra}:security-group-rule/*"
      }),
    ]
  }

  # Dedicated: the service's own security group, launch template, ASG, bucket,
  # SSM document and instance role.
  st_infra_dedicated = {
    for repository, c in local.ctx : repository => [

      # --- its own security group ---------------------------------------------
      jsonencode({
        Sid      = "CreateSecurityGroupInAVpc"
        Effect   = "Allow"
        Action   = ["ec2:CreateSecurityGroup"]
        Resource = "arn:aws:ec2:${local.ra}:vpc/*"
      }),
      jsonencode({
        Sid       = "CreateSecurityGroupTaggedForThisService"
        Effect    = "Allow"
        Action    = ["ec2:CreateSecurityGroup"]
        Resource  = "arn:aws:ec2:${local.ra}:security-group/*"
        Condition = { StringEquals = { "aws:RequestTag/Service" = c.service } }
      }),
      jsonencode({
        Sid    = "ManageOwnSecurityGroups"
        Effect = "Allow"
        Action = [
          "ec2:AuthorizeSecurityGroupEgress", "ec2:AuthorizeSecurityGroupIngress", "ec2:DeleteSecurityGroup",
          "ec2:ModifySecurityGroupRules", "ec2:RevokeSecurityGroupEgress", "ec2:RevokeSecurityGroupIngress",
          "ec2:UpdateSecurityGroupRuleDescriptionsEgress", "ec2:UpdateSecurityGroupRuleDescriptionsIngress",
        ]
        Resource  = "arn:aws:ec2:${local.ra}:security-group/*"
        Condition = { StringEquals = { "ec2:ResourceTag/Service" = c.service } }
      }),
      jsonencode({
        Sid      = "SecurityGroupRules"
        Effect   = "Allow"
        Action   = ["ec2:ModifySecurityGroupRules", "ec2:CreateTags", "ec2:DeleteTags"]
        Resource = "arn:aws:ec2:${local.ra}:security-group-rule/*"
      }),

      # --- launch template and the instances it starts -------------------------
      jsonencode({
        Sid       = "CreateLaunchTemplateTaggedForThisService"
        Effect    = "Allow"
        Action    = ["ec2:CreateLaunchTemplate"]
        Resource  = "arn:aws:ec2:${local.ra}:launch-template/*"
        Condition = { StringEquals = { "aws:RequestTag/Service" = c.service } }
      }),
      jsonencode({
        Sid    = "ManageOwnLaunchTemplates"
        Effect = "Allow"
        Action = [
          "ec2:CreateLaunchTemplateVersion", "ec2:DeleteLaunchTemplate", "ec2:DeleteLaunchTemplateVersions",
          "ec2:ModifyLaunchTemplate",
        ]
        Resource  = "arn:aws:ec2:${local.ra}:launch-template/*"
        Condition = { StringEquals = { "ec2:ResourceTag/Service" = c.service } }
      }),
      jsonencode({
        Sid      = "TagOnCreate"
        Effect   = "Allow"
        Action   = ["ec2:CreateTags"]
        Resource = "arn:aws:ec2:${local.ra}:*/*"
        Condition = {
          StringEquals = {
            "ec2:CreateAction"       = ["CreateLaunchTemplate", "CreateSecurityGroup", "RunInstances"]
            "aws:RequestTag/Service" = c.service
          }
        }
      }),
      # An ASG's launch template is checked against the caller's permissions.
      jsonencode({
        Sid      = "RunInstancesTaggedForThisService"
        Effect   = "Allow"
        Action   = ["ec2:RunInstances"]
        Resource = ["arn:aws:ec2:${local.ra}:instance/*", "arn:aws:ec2:${local.ra}:network-interface/*", "arn:aws:ec2:${local.ra}:volume/*"]
        Condition = {
          StringEquals = { "aws:RequestTag/Service" = c.service }
        }
      }),
      jsonencode({
        Sid    = "RunInstancesSupportingResources"
        Effect = "Allow"
        Action = ["ec2:RunInstances"]
        Resource = [
          "arn:aws:ec2:${local.ra}:image/*", "arn:aws:ec2:${local.ra}:launch-template/*",
          "arn:aws:ec2:${local.ra}:security-group/*", "arn:aws:ec2:${local.ra}:spot-instances-request/*",
          "arn:aws:ec2:${local.ra}:subnet/*",
        ]
      }),

      # --- its own auto scaling group ------------------------------------------
      jsonencode({
        Sid    = "OwnAutoScalingGroup"
        Effect = "Allow"
        Action = ["autoscaling:*"]
        # terraform-aws-autoscaling names a group <project>-<environment>-<service>-asg,
        # which is not this policy's usual <project>-<service>-<environment>
        # order. The name is the module's, so the policy follows it.
        Resource = [
          "arn:aws:autoscaling:${local.ra}:autoScalingGroup:*:autoScalingGroupName/${var.project_name}-${var.environment}-${c.service}-asg",
          "arn:aws:autoscaling:${local.ra}:scalingPolicy:*:autoScalingGroupName/${var.project_name}-${var.environment}-${c.service}-asg:policyName/*",
        ]
      }),
      jsonencode({
        Sid      = "ReadPublicAmiParameters"
        Effect   = "Allow"
        Action   = ["ssm:GetParameter"]
        Resource = "arn:aws:ssm:${var.aws_region}::parameter/aws/service/*"
      }),

      # --- its own configuration bucket and update document --------------------
      jsonencode({
        Sid      = "OwnConfigurationBucket"
        Effect   = "Allow"
        Action   = ["s3:*"]
        Resource = ["arn:aws:s3:::${c.config_bucket}", "arn:aws:s3:::${c.config_bucket}/*"]
      }),
      jsonencode({
        Sid    = "OwnUpdateDocument"
        Effect = "Allow"
        Action = [
          "ssm:AddTagsToResource", "ssm:CreateDocument", "ssm:DeleteDocument", "ssm:DescribeDocument",
          "ssm:GetDocument", "ssm:ListTagsForResource", "ssm:RemoveTagsFromResource", "ssm:UpdateDocument",
          "ssm:UpdateDocumentDefaultVersion",
        ]
        Resource = "arn:aws:ssm:${local.ra}:document/${var.project_name}-${c.service}-*"
      }),

      # --- the instance role, capped by the permissions boundary ---------------
      jsonencode({
        Sid       = "CreateRolesOnlyWithTheBoundary"
        Effect    = "Allow"
        Action    = ["iam:CreateRole"]
        Resource  = "${local.iam}:role/services/${c.service}/*"
        Condition = { StringEquals = { "iam:PermissionsBoundary" = local.boundary_arn, "aws:RequestTag/Service" = c.service } }
      }),
      jsonencode({
        Sid       = "SetOnlyTheBoundary"
        Effect    = "Allow"
        Action    = ["iam:PutRolePermissionsBoundary"]
        Resource  = "${local.iam}:role/services/${c.service}/*"
        Condition = { StringEquals = { "iam:PermissionsBoundary" = local.boundary_arn } }
      }),
      jsonencode({
        Sid    = "ManageOwnRoles"
        Effect = "Allow"
        Action = [
          "iam:AttachRolePolicy", "iam:DeleteRole", "iam:DeleteRolePolicy", "iam:DetachRolePolicy",
          "iam:PutRolePolicy", "iam:UpdateAssumeRolePolicy", "iam:UpdateRole", "iam:UpdateRoleDescription",
        ]
        Resource = "${local.iam}:role/services/${c.service}/*"
      }),
      jsonencode({
        Sid       = "TagOwnRolesWithTheirService"
        Effect    = "Allow"
        Action    = ["iam:TagRole"]
        Resource  = "${local.iam}:role/services/${c.service}/*"
        Condition = { StringEquals = { "aws:RequestTag/Service" = c.service } }
      }),
      jsonencode({
        Sid    = "OwnPoliciesAndInstanceProfiles"
        Effect = "Allow"
        Action = [
          "iam:AddRoleToInstanceProfile", "iam:CreateInstanceProfile", "iam:CreatePolicy", "iam:CreatePolicyVersion",
          "iam:DeleteInstanceProfile", "iam:DeletePolicy", "iam:DeletePolicyVersion", "iam:RemoveRoleFromInstanceProfile",
          "iam:SetDefaultPolicyVersion", "iam:TagInstanceProfile", "iam:TagPolicy", "iam:UntagInstanceProfile",
          "iam:UntagPolicy",
        ]
        Resource = [
          "${local.iam}:instance-profile/services/${c.service}/*",
          "${local.iam}:policy/services/${c.service}/*",
        ]
      }),
      jsonencode({
        Sid       = "PassOwnRolesToEc2Only"
        Effect    = "Allow"
        Action    = ["iam:PassRole"]
        Resource  = "${local.iam}:role/services/${c.service}/*"
        Condition = { StringEquals = { "iam:PassedToService" = "ec2.amazonaws.com" } }
      }),
      jsonencode({
        Sid    = "ReadOwnIam"
        Effect = "Allow"
        Action = ["iam:Get*", "iam:List*"]
        Resource = [
          "${local.iam}:role/services/${c.service}/*",
          "${local.iam}:instance-profile/services/${c.service}/*",
          "${local.iam}:policy/services/${c.service}/*",
        ]
      }),
      jsonencode({
        Sid      = "ServiceLinkedRolesForScalingAndSpot"
        Effect   = "Allow"
        Action   = ["iam:CreateServiceLinkedRole"]
        Resource = ["${local.iam}:role/aws-service-role/autoscaling.amazonaws.com/*", "${local.iam}:role/aws-service-role/spot.amazonaws.com/*"]
        Condition = {
          StringEquals = { "iam:AWSServiceName" = ["autoscaling.amazonaws.com", "spot.amazonaws.com"] }
        }
      }),

      # --- the guard rails: these override every Allow above -------------------
      jsonencode({
        Sid      = "NeverRemoveTheBoundaryFromARole"
        Effect   = "Deny"
        Action   = ["iam:DeleteRolePermissionsBoundary"]
        Resource = "*"
      }),
      jsonencode({
        Sid       = "NeverRemoveTheServiceTag"
        Effect    = "Deny"
        Action    = ["iam:UntagRole"]
        Resource  = "*"
        Condition = { "ForAnyValue:StringEquals" = { "aws:TagKeys" = ["Service"] } }
      }),
      jsonencode({
        Sid      = "NeverChangeTheBoundaryPolicy"
        Effect   = "Deny"
        Action   = ["iam:CreatePolicyVersion", "iam:DeletePolicy", "iam:DeletePolicyVersion", "iam:SetDefaultPolicyVersion"]
        Resource = local.boundary_arn
      }),
    ]
  }

  ##############################################################################
  # THE FINAL POLICY -- by kind and hosting model
  ##############################################################################

  statements = {
    for repository, c in local.ctx : repository => (
      c.kind == "app"
      ? concat(
        [local.st_ecr_login, local.st_ecr_push[repository], local.st_read_platform[repository], local.st_lookups_app],
        local.st_static[repository],
        local.st_app_hosting[repository],
      )
      : concat(
        [local.st_lookups_infra],
        local.st_infra_common[repository],
        local.st_infra_provisioning[repository],
        local.st_infra_managed_provisioning[repository],
        local.st_infra_front_door[repository],
        local.dedicated ? local.st_infra_dedicated[repository] : local.st_infra_shared[repository],
      )
    )
  }

  # The whole of each role's permissions as one document, for review and tests.
  policies = {
    for repository, statements in local.statements :
    repository => "{\"Version\":\"2012-10-17\",\"Statement\":[${join(",", statements)}]}"
  }

  ##############################################################################
  # MANAGED POLICIES -- the statements, STATEMENTS_PER_POLICY at a time
  ##############################################################################

  # The largest statement today is about 540 characters (the longest service name
  # in a long Region name), so 8 of them come to about 4,400: each could still
  # grow by 40% before a policy reached IAM's 6,144.
  statements_per_policy  = 8
  managed_policy_limit   = 6144
  managed_policies_limit = 10 # IAM's default for managed policies attached to one role

  policy_chunks = {
    for repository, statements in local.statements : repository => [
      for index in range(ceil(length(statements) / local.statements_per_policy)) :
      "{\"Version\":\"2012-10-17\",\"Statement\":[${join(",", slice(
        statements,
        index * local.statements_per_policy,
        min(length(statements), (index + 1) * local.statements_per_policy)
      ))}]}"
    ]
  }

  # One entry per managed policy. The keys use only the repository and the
  # policy's position, both known at plan.
  managed_policies = merge([
    for repository, chunks in local.policy_chunks : {
      for index, document in chunks : "${repository}#${index + 1}" => {
        repository = repository
        name       = "${var.project_name}-${var.environment}-${local.ctx[repository].service}-${local.ctx[repository].kind}-${index + 1}"
        document   = document
      }
    }
  ]...)

  # Each policy's ARN, built rather than read from the resource: the OIDC module
  # keys its attachments by ARN, and a resource's ARN is unknown until it exists,
  # which a first plan cannot use. IAM's format is arn:aws:iam::<account>:policy
  # <path><name>; were it ever different, attaching would fail at apply with
  # IAM's own "no such policy" error.
  managed_policy_path = "/platform/service-roles/"

  managed_policy_arns = {
    for key, policy in local.managed_policies : key => "${local.iam}:policy${local.managed_policy_path}${policy.name}"
  }

  too_many_policies = [
    for repository, chunks in local.policy_chunks : repository if length(chunks) > local.managed_policies_limit
  ]

  oversized_policies = [
    for key, policy in local.managed_policies : key if length(policy.document) > local.managed_policy_limit
  ]
}
