# ------------------------------------------------------------------------------
# SERVICE ROLES
#
# Turns the entries of service-roles.json into the input of the OIDC module's
# service_roles: for each repository, the token subjects to trust and a scoped
# inline policy.
#
# TWO ROLES PER SERVICE. A service has two repositories with different jobs, so
# each gets a role that can do only its own job:
#
#   kind "infra"  the repository holding the service's Terraform. It creates and
#                 changes the service's cloud resources, so it holds the
#                 Terraform-scale permissions -- including, in a dedicated
#                 environment, IAM, limited by a permissions boundary.
#   kind "app"    the repository that builds and deploys the application. It
#                 pushes an image, publishes files and triggers a redeploy. It
#                 holds no permission to create or change any resource, and none
#                 over IAM.
#
# The two find each other through one SSM parameter per service,
# /<project>/services/<service>/config, which the infra role writes and the app
# role reads.
#
# THE POLICY IS GENERATED, NOT HAND-WRITTEN. It is built from the service's name
# and tier, so every resource it names carries that service's own name -- the ECR
# repository <service>/*, the secret <project>-<service>-<env>-secret-vault, the
# target group <project>-<service>-<env>-tg, the S3 prefixes, its own state key,
# and (dedicated) its own ASG, security group, bucket and IAM path /services/<service>/.
#
# HOSTING MODELS
#   shared        development: services run on the shared tier fleets.
#   dedicated     staging and production: each service's infra repository creates
#                 its own launch template, ASG, security group, configuration
#                 bucket and instance role. The role it creates must carry the
#                 permissions boundary, so it can never be more powerful than the
#                 boundary allows, whatever is attached to it.
#
# WHAT AWS CANNOT SCOPE. Some actions cannot be limited to one service:
#   - ecr:GetAuthorizationToken and the Describe* read calls need "*".
#   - shared: the shared tier security group can be changed by any service's
#     infra role and AWS cannot limit which port or source a rule opens; a target
#     group can be detached from the shared ASG by any service. Rely on review.
#   - dedicated: launch-template and security-group resources have no name in their
#     ARN, so they are scoped by the Service tag instead of by name.
# ALB rules ARE protected: a rule may only be created with, and later changed only
# while it carries, a Service tag equal to the service's name.
#
# Where an action list would run to a dozen names, a wildcard is used instead
# (secretsmanager:* on the service's own secret, autoscaling:* on its own group,
# iam:Get*/List* on its own IAM path): the RESOURCE is what confines it.
#
# MANAGED POLICIES, NOT ONE INLINE POLICY. IAM allows a role 10,240 characters of
# inline policy; a dedicated infra role with three engines and the front door
# needs more (about 10,300 for a short service name, 10,700 for the longest). So
# each role's statements are published as managed policies, STATEMENTS_PER_POLICY
# at a time (at most 6,144 characters each, and at most 10 per role). The split
# is by number of statements, never by their length: some statements hold values
# known only after apply, and the number of policies must be known at plan.
#
# They live under /platform/service-roles/, not the service's own IAM path
# /services/<service>/: a dedicated infra role may create and change policies
# there, and must never be able to change its own permissions.
#
# THE DEDICATED POLICY IS A FIRST DRAFT for resources whose creation has not yet
# been exercised against AWS. Its first real plan is the test; expect to add an
# action or two. Managed databases are not covered yet.
#
# Each policy is built as a list of JSON statements (strings) so the four
# variants -- app and infra, shared and dedicated -- can be concatenated without
# Terraform needing their differently-shaped objects to unify. policy_sizes
# reports each managed policy's size.
# ------------------------------------------------------------------------------

resource "aws_iam_policy" "service" {
  for_each = local.managed_policies

  name        = each.value.name
  path        = local.managed_policy_path
  description = "Part of the CI permissions of ${each.value.repository} (service ${local.ctx[each.value.repository].service}, ${local.ctx[each.value.repository].kind}) in ${var.environment}. Generated by core; do not edit."
  policy      = each.value.document

  depends_on = [terraform_data.service_roles_invariants]

  lifecycle {
    # Known only once every value in the statements is: checked at apply, before
    # IAM would refuse it.
    precondition {
      condition     = length(each.value.document) <= local.managed_policy_limit
      error_message = "${each.value.name} is ${length(each.value.document)} characters, over IAM's ${local.managed_policy_limit} for a managed policy. Lower statements_per_policy in modules/platform/service-roles/main.tf rather than trimming what the role needs."
    }
  }
}

module "identity" {
  source   = "../identity"
  for_each = var.entries

  github_repository    = each.key
  github_owner_id      = each.value.owner_id
  github_repository_id = each.value.repository_id
  subject_format       = var.subject_format
  environment          = var.environment
}

resource "terraform_data" "service_roles_invariants" {
  lifecycle {
    precondition {
      condition     = length(local.invalid_repository_keys) == 0
      error_message = "service-roles.json keys must be OWNER/REPOSITORY. Invalid: ${join(", ", local.invalid_repository_keys)}."
    }

    precondition {
      condition     = length(local.invalid_kinds) == 0
      error_message = "Every entry needs kind \"app\" or \"infra\". Invalid: ${join(", ", local.invalid_kinds)}."
    }

    precondition {
      condition     = length(local.invalid_service_names) == 0
      error_message = "service_name must be 3-22 lowercase letters, digits or hyphens, starting with a letter, and short enough that ${var.project_name}-<service>-${var.environment}-tg fits AWS's 32-character target group name limit. Invalid: ${join(", ", local.invalid_service_names)}."
    }

    precondition {
      condition     = length(local.reserved_names_used) == 0
      error_message = "These service names are reserved because the platform's own resources use them (${join(", ", local.reserved_service_names)}, and any name beginning ${join(" or ", local.reserved_service_prefixes)}): ${join(", ", local.reserved_names_used)}."
    }

    precondition {
      condition     = length(distinct(local.entry_keys)) == length(local.entry_keys)
      error_message = "A service may have at most one \"app\" and one \"infra\" entry. Two entries share a kind and a service_name."
    }

    precondition {
      condition     = length(local.services_with_conflicting_tiers) == 0
      error_message = "A service's app and infra entries must name the same tier. Conflicting: ${join(", ", local.services_with_conflicting_tiers)}."
    }

    precondition {
      condition     = length(local.entries_with_unknown_tier) == 0
      error_message = "These entries name a tier that does not exist in this environment: ${join(", ", local.entries_with_unknown_tier)}. Available tiers: ${join(", ", keys(var.tiers))}. The internal tier exists only while internal_tier_enabled is on in this environment's terraform.tfvars."
    }

    precondition {
      condition     = length(local.missing_inputs) == 0
      error_message = "service-roles.json has entries, so these inputs are required but not set: ${join(", ", local.missing_inputs)}."
    }

    precondition {
      condition     = length(local.too_many_policies) == 0
      error_message = "These roles would need more than IAM's ${local.managed_policies_limit} managed policies: ${join(", ", local.too_many_policies)}. Raise statements_per_policy in modules/platform/service-roles/main.tf if every policy still fits ${local.managed_policy_limit} characters, or ask AWS to raise the limit."
    }

    precondition {
      condition     = length(local.oversized_policies) == 0
      error_message = "These generated policies exceed IAM's ${local.managed_policy_limit}-character limit for a managed policy: ${join(", ", local.oversized_policies)}. Lower statements_per_policy in modules/platform/service-roles/main.tf rather than trimming what a role legitimately needs."
    }

    precondition {
      condition     = length(local.infra_missing_fleet_resources) == 0
      error_message = "Shared-fleet hosting needs each tier's asg_arn and security_group_id. Missing for: ${join(", ", local.infra_missing_fleet_resources)}."
    }
  }
}
